Задачи 7-9
FormalLanguageConstrainedPathQuerying/formal-lang-course pull request #132
Opened 2024-04-05 10:41 UTC by gsvgit

* Перенумерованы и почищены существующие задачи по КС достижимости.
* Добавлена задача на КС достижимость с использованием GLL и  RSM

2024-04-08 08:17 UTC, WoWaster requested changes

2024-04-08 08:17 UTC, WoWaster commented on tasks/task9.md
> +- [ ] Реализовать **функцию**, основанную на алгоритме GLL (работающего RSM), решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики.
Тут что-то не очень читаемое

2024-04-08 08:59 UTC, KubEF approved these changes

2024-04-08 18:45 UTC, WoWaster approved these changes

2024-04-09 07:32 UTC, WoWaster commented
Это же решает #129?

2024-04-09 11:44 UTC, merged