Задача 12. Про парсер. Описание языка.
FormalLanguageConstrainedPathQuerying/formal-lang-course pull request #134
Opened 2024-04-19 10:07 UTC by gsvgit

2024-04-19 10:59 UTC, WoWaster requested changes
Остальное -- ок. Но надо бы подчистить остальные задачи, иначе беда с нумерацией и вообще путает всех :(

2024-04-19 10:59 UTC, WoWaster commented on tasks/task12.md
task12.md, в заголовке "Задача 13", а по факту вообще 11 :)

2024-04-19 10:59 UTC, WoWaster commented on tasks/task12.md
> +[Smb (e)](b) => FA
`Smb` -- есть Symbol?

2024-04-19 10:59 UTC, WoWaster commented on tasks/task12.md
> +- [ ] Реализовать функцию, которая по дереву разбора строит строку, которая была разобрана.
Типизация уходит в задачку про интерпретатор, да?

2024-04-19 11:06 UTC, gsvgit commented on tasks/task12.md
> +[Smb (e)](b) => FA
Да.

2024-04-19 11:07 UTC, gsvgit commented on tasks/task12.md
Да... Ща.

2024-04-19 11:32 UTC, WoWaster requested changes

2024-04-19 11:32 UTC, WoWaster commented on tasks/task10.md
Должно быть два файла с одним заголовком?

2024-04-19 11:32 UTC, WoWaster commented on tasks/task10.md
> +* **Жёсткий дедлайн**: !!!, 23:59
Дедлайны здесь мы вроде бы уже знаем

2024-04-19 11:32 UTC, WoWaster commented on tasks/task12.md
> +# Задача 12. Интерпретатор языка запросов к графам
Тут текст ещё будет правиться?

2024-04-19 11:32 UTC, WoWaster commented on tasks/task11.md
> +# Задача 11. Язык запросов к графам
Я посмотрел на текст 12 задачи. Я правильно понимаю, что реализовывать `print` и вообще человеко-читаемый вывод, например исключений, особо не надо и достаточно адекватной архитектуры с точки зрения питона?

2024-04-19 15:24 UTC, KubEF commented on tasks/task11.md
> +select = v_filter? v_filter? 'return' VAR (',' VAR)? 'where' VAR 'reachable' 'from' VAR 'in' VAR 'by' expr
Тут как будто вместо второго `v_filter?` должен быть `set_expr?`. По крайнер мере в примере так вроде.

2024-04-19 17:06 UTC, gsvgit commented on tasks/task11.md
> +select = v_filter? v_filter? 'return' VAR (',' VAR)? 'where' VAR 'reachable' 'from' VAR 'in' VAR 'by' expr
@KubEF не. Тут не больше двух фильтров: по количеству концов у путей. Например, можно написать
```
let r = for v in [1,2] for u in [3,4] return v,u where u reachable from v in g by q
```

2024-04-19 17:07 UTC, gsvgit commented on tasks/task11.md
Да. Подразумевается, что должны быть ещё типы, которые решат такие проблемы. А чисто синтаксически написать можно много всякой ерунды. Ну и не совсем: в v_filter можно использовать всё, что вычисляется в множеству. Например, результат вычисления запроса.

2024-04-20 05:44 UTC, gsvgit commented
Вроде попробовал причесать всё, что 10--12. Бонусную 10 пока не намерен давать, но пусть будет. Постараюсь сегодня ещё написать, как 12 тестировать.

2024-04-20 07:59 UTC, WoWaster approved these changes
Кроме одной мини-очепятки, всё ок. Все свои вопросы выше позакрывал

2024-04-20 07:59 UTC, WoWaster commented on tasks/task12.md
> +В данной задаче необходимо разработать интерпретатор языка запросов, разработанного в предыдущей работе. Для исполнения запросов использовать алгоритмы, реализованные в предыдущих работах. КРоме реал
КРоме

2024-04-20 09:15 UTC, merged