Автотесты для 11 домашки
FormalLanguageConstrainedPathQuerying/formal-lang-course pull request #140
Opened 2024-04-30 07:07 UTC by KubEF

Во-первых, надо доделать скриптик, чтобы генерились и подтягивались тестовые случаи кода, Это на @WoWaster. А во-вторых,  я добавил один случай: просто проверку на то, что parsing -> generation -- это id  в терминах кода, как будто получилось маловато.

2024-04-30 07:25 UTC, gsvgit requested changes

2024-04-30 07:25 UTC, gsvgit commented on tasks/task11.md
> +range = '[' NUM ('..' NUM)? ']'
Нет, именно так, как было написано: ```[0 .. ]``` Типа, от нуля до бесконечности.

2024-04-30 07:25 UTC, gsvgit commented on tasks/task11.md
> -add edge (1, "a", 2) to g
А за что это удалили? Вроде нормальная конструкция.

2024-04-30 07:25 UTC, gsvgit commented on tests/autotests/test_task11.py
> +# it will be filled by script? In some way
Я думаю, что можно просто сгенерированный файл выложить рядом и читать его. Или файлы, как проще. "Спрятать" только граммтику надо, чтобы совсем уж не скатывали.

2024-04-30 07:25 UTC, gsvgit commented on tests/autotests/test_task11.py
> +        tree_before = prog_to_tree(program)
Ща. Я ожидал, что фаззер нагенерирует как корректные, так и некорректные строки. Это не так?

2024-04-30 08:57 UTC, KubEF commented on tests/autotests/test_task11.py
> +        tree_before = prog_to_tree(program)
Насколько я понимаю, нет. А вам ещё хочется генерировать похожие на правду строки, но которые по сути не будут правильными (например, ` let A is graph` ), или просто рандомные строки, которые никак грамматику не используют (ну, максимум проверяют, чтобы случайно не сгенерировалась корректная)?

2024-04-30 08:59 UTC, KubEF commented on tasks/task11.md
> -add edge (1, "a", 2) to g
Это я сам там что-то менял и видимо запутался, когда ребейзился

2024-04-30 09:02 UTC, KubEF commented on tests/autotests/test_task11.py
> +# it will be filled by script? In some way
Вы имеете в виду сгенерировать один раз много случаев, которые будут одинаковыми для всех? Я думал, просто, чтобы там генерировались строки новые каждый раз, когда запускаются тесты

2024-04-30 09:07 UTC, gsvgit commented on tests/autotests/test_task11.py
> +# it will be filled by script? In some way
Пожалуй, как Вы предлагаете, даже правильнее. Тогда там, правда, не просто список будет, а, видимо, вызов генератора.

2024-04-30 09:12 UTC, gsvgit commented on tests/autotests/test_task11.py
> +        tree_before = prog_to_tree(program)
Ну тогда надо повносить каких-то контролируемых изменений и получить некорректные входы. Иначе напишут грамматику для \Sigma^*. Можно, например, из корректных строк поудалять что-нибудь обязательное типа запятых, равества, ещё чего-то. Правда, думаю, лучше проверять, что сдучайно всё ещё не осалась корректной. Если осталась --- это будет загадочно, кстати.

2024-04-30 10:00 UTC, KubEF commented on tests/autotests/test_task11.py
> +        tree_before = prog_to_tree(program)
В смысле попросить их добавить ещё функцию, которая проверяет валидность строки и использовать её, или как-то самому делать?

2024-04-30 10:50 UTC, gsvgit commented on tests/autotests/test_task11.py
> +        tree_before = prog_to_tree(program)
Ща... Тут уже я не понял. ANTLR, конечно, и для некорректного входа может дерево построить, но в реальной жизни всё равно нужна диагностика. Ну то есть я думаю, что мы заранее должны знать, что строка корректна или нет, а потом смотреть, что у судентов на этой строке. На корректной должно сщйтись количество узлов, а для некорректной надо получить хотя бы просто сообщение о том, что она некорректна.

2024-04-30 10:51 UTC, gsvgit commented on tasks/task11.md
> +def prog_to_tree(program: str) ->  ProgContex:
Ну да. Вот тут бы возвращать пару типа "дерево+статус (корректна или нет)". Хотя статус и в ProgContext, вроде, есть. Так что может и не надо.

2024-05-03 13:49 UTC, WoWaster commented on tests/autotests/test_task11.py
> +            assert not is_valid_bad
Мне кажется, что если мы оставляется тесты на некорректность, то их надо в отдельную функцию

2024-05-04 16:45 UTC, WoWaster commented on tasks/task11.md
>  - [ ] Реализовать функцию, которая по дереву разбора строит строку, которая была разобрана.
Надо бы ещё вернуть слова, что классы надо генерировать в CI, а не класть в гит

2024-05-06 08:07 UTC, gsvgit commented
Обновить, так как обновились регулярки для чисел и идентификаторов.

2024-05-06 08:16 UTC, WoWaster commented
Обновил ветку force push'ем. @KubEF не забудь обновить локально

2024-05-06 08:51 UTC, gsvgit approved these changes

2024-05-06 08:51 UTC, merged